version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels: ["deps", "autobot"]
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
