name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## What's Changed
  
  $CHANGES
categories:
  - title: '🚀 Features'
    labels: [feature, enhancement]
  - title: '🐛 Fixes'
    labels: [bug, fix]
  - title: '🧰 Chore'
    labels: [chore, refactor, docs]
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No user-facing changes.'