title = "Linguamate Gitleaks Configuration"

[allowlist]
description = "False positives and test fixtures for Linguamate project"
files = [
  "tests/fixtures/.*",
  "docs/snippets/.*",
  "**/*.test.*",
  "**/*.spec.*",
  "**/__tests__/.*",
  "**/test-utils/.*"
]

# Allow common test patterns and dummy values
regexes = [
  # Test API keys and tokens
  '''(?i)(test|dummy|fake|mock)_(api|token|key|secret)_[0-9a-f]{8,32}''',
  '''(?i)(test|dummy|fake|mock)_(password|pwd|pass)_[0-9a-f]{8,32}''',
  
  # Common test patterns
  '''(?i)test.*[0-9a-f]{32}''',
  '''(?i)dummy.*[0-9a-f]{32}''',
  '''(?i)example.*[0-9a-f]{32}''',
  
  # Public keys (safe to commit)
  '''-----BEGIN PUBLIC KEY-----[\s\S]*-----END PUBLIC KEY-----''',
  
  # Common hash patterns that aren't secrets
  
  # Common test database URLs
  '''postgresql://test:test@localhost:5432/test''',
  '''mysql://test:test@localhost:3306/test''',
  '''mongodb://test:test@localhost:27017/test''',
  
  # Common test JWT tokens (obviously fake)
  '''eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9\..*''',
  
  # Common test email patterns
  '''test@example\.com''',
  '''admin@test\.com''',
  '''user@localhost''',
  
  # Common test phone numbers
  '''\+1-555-0123''',
  '''555-0123''',
  
  # Common test credit card patterns (Luhn test numbers)
  '''4[0-9]{12}(?:[0-9]{3})?''',  # Visa test numbers
  '''5[1-5][0-9]{14}''',           # MasterCard test numbers
]

# Allow specific file patterns that commonly contain test data
[allowlist.paths]
paths = [
  "**/test/**",
  "**/tests/**",
  "**/__tests__/**",
  "**/fixtures/**",
  "**/mocks/**",
  "**/stubs/**",
  "**/examples/**",
  "**/samples/**",
  "**/demos/**",
  "**/playground/**",
  "**/sandbox/**"
]