# Gitleaks configuration for Linguamate AI Tutor
# This configuration helps detect secrets and sensitive information

[gitleaks]
  # Scan only staged files by default
  staged = false
  # Don't scan git history by default
  history = false
  # Verbose output
  verbose = true
  # Redact secrets in output
  redact = true

# Rules for detecting secrets
[[rules]]
  description = "Generic API Key"
  regex = '''(?i)(api[_-]?key|apikey|api_key|api-key)\s*[:=]\s*['"]?[a-zA-Z0-9]{20,}['"]?'''
  tags = ["key", "api"]

[[rules]]
  description = "Generic Secret"
  regex = '''(?i)(secret|password|passwd|pwd)\s*[:=]\s*['"]?[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{}|;':",./<>?]{8,}['"]?'''
  tags = ["secret", "password"]

[[rules]]
  description = "JWT Token"
  regex = '''eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'''
  tags = ["jwt", "token"]

[[rules]]
  description = "AWS Access Key"
  regex = '''AKIA[0-9A-Z]{16}'''
  tags = ["aws", "key"]

[[rules]]
  description = "AWS Secret Key"
  regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key\s*[:=]\s*['"]?[a-zA-Z0-9/+=]{40}['"]?'''
  tags = ["aws", "secret"]

[[rules]]
  description = "GitHub Token"
  regex = '''ghp_[a-zA-Z0-9]{36}'''
  tags = ["github", "token"]

[[rules]]
  description = "OpenAI API Key"
  regex = '''sk-[a-zA-Z0-9]{48}'''
  tags = ["openai", "api", "key"]

[[rules]]
  description = "Database URL"
  regex = '''(?i)(mongodb|postgres|mysql|redis)://[^\s]+'''
  tags = ["database", "url"]

[[rules]]
  description = "Private Key"
  regex = '''-----BEGIN [A-Z ]+ PRIVATE KEY-----'''
  tags = ["private", "key"]

# Exclude certain files and directories
[gitleaks.allowlist]
  description = "Allowlist for Linguamate"
  files = [
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "*.lock",
    "*.log",
    "node_modules/**",
    ".git/**",
    "dist/**",
    "build/**",
    "coverage/**",
    ".next/**",
    ".expo/**"
  ]