on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]
    paths-ignore:
      - "FILES_TREE.md"
  schedule:
    - cron: "0 6 * * 1" # Every Monday 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate FILES_TREE.md
        shell: bash
        run: |
          set -euo pipefail

          IGNORE='node_modules|.git|.expo|dist|build|.next|.vercel|.turbo|coverage|.cache|ios|android|.vscode|.idea'
          DEPTH=50

          # Utility to write a section with TOC anchor
          write_section () {
            local title="$1"
            local dir="$2"
            echo -e "\n## ${title}\n" >> FILES_TREE.md
            if [ -d "$dir" ]; then
              tree -a -I "$IGNORE" -L $DEPTH "$dir" >> FILES_TREE.md
            else
              echo "_(folder not present)_" >> FILES_TREE.md
            fi
            echo >> FILES_TREE.md
          }

          # Header
          {
            echo "# Repository File Tree"
            echo
            echo "> Auto-generated by GitHub Actions ($(date -u +'%Y-%m-%d %H:%M UTC'))."
            echo
            echo "## Table of Contents"
            echo "- [Root](#root)"
            echo "- [app](#app)"
            echo "- [components](#components)"
            echo "- [backend](#backend)"
            echo "- [schemas](#schemas)"
            echo "- [modules](#modules)"
            echo "- [lib](#lib)"
            echo "- [hooks](#hooks)"
            echo "- [state](#state)"
            echo "- [types](#types)"
            echo "- [constants](#constants)"
            echo "- [assets/images](#assetsimages)"
            echo "- [tests](#tests)"
            echo "- [__tests__](#__tests__)"
            echo "- [docs](#docs)"
            echo "- [scripts](#scripts)"
            echo "- [observability](#observability)"
            echo "- [home/project](#homeproject)"
            echo "- [reports](#reports)"
            echo
            echo "## Root"
            # Root files only (no recursion)
            tree -a -I "$IGNORE" -L 1 -F | sed '1d'
          } > FILES_TREE.md

          # Key sections (deep)
          write_section "app" "app"
          write_section "components" "components"
          write_section "backend" "backend"
          write_section "schemas" "schemas"
          write_section "modules" "modules"
          write_section "lib" "lib"
          write_section "hooks" "hooks"
          write_section "state" "state"
          write_section "types" "types"
          write_section "constants" "constants"
          write_section "assets/images" "assets/images"
          write_section "tests" "tests"
          write_section "__tests__" "__tests__"
          write_section "docs" "docs"
          write_section "scripts" "scripts"
          write_section "observability" "observability"
          write_section "home/project" "home/project"
          write_section "reports" "reports"

      - name: Commit and push (skip if no change)
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- FILES_TREE.md; then
            git add FILES_TREE.md
            git commit -m "chore: auto-update FILES_TREE.md"
            git push
          else
            echo "No changes to FILES_TREE.md"
          fi
