name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: Tell us what actually happened...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - iOS
        - Android
        - Web
        - All platforms
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device/Browser
      description: e.g., iPhone 14, Samsung Galaxy S21, Chrome 120
      placeholder: Device model or browser version
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: e.g., iOS 17.1, Android 14, Windows 11
      placeholder: Operating system version
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Version of the app where the bug occurs
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always
        - Often (>50%)
        - Sometimes (10-50%)
        - Rarely (<10%)
        - Only once
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: Network Conditions
      description: Does this bug occur under specific network conditions?
      options:
        - Any network
        - Only on WiFi
        - Only on cellular
        - Only offline
        - Only on slow connections
    validations:
      required: true

  - type: input
    id: error-id
    attributes:
      label: Error ID
      description: If the app showed an error ID, please provide it
      placeholder: e.g., error_1234567890_abc123

  - type: input
    id: request-id
    attributes:
      label: Request ID
      description: If available, provide the request ID from network logs
      placeholder: e.g., req_1234567890_xyz789

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Please paste any relevant console logs here
      render: shell
      placeholder: |
        Paste console output here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: |
        Add screenshots or videos to help explain your problem.
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: Drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all that apply
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all required information above
          required: true
        - label: I have tried reproducing in a clean environment/incognito mode
          required: false
        - label: I have checked the browser console for errors
          required: false

  - type: dropdown
    id: impact
    attributes:
      label: Business Impact
      description: How does this bug impact your usage?
      options:
        - Critical - Cannot use the app
        - High - Major feature unusable
        - Medium - Feature partially broken
        - Low - Minor inconvenience
    validations:
      required: true