blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/ayais12210-hub/Linguamate-ai-tutor/security/advisories/new
    about: Please report security vulnerabilities here
  - name: Feature Request
    url: https://github.com/ayais12210-hub/Linguamate-ai-tutor/discussions/new?category=ideas
    about: Suggest new features or improvements
  - name: Questions & Support
    url: https://github.com/ayais12210-hub/Linguamate-ai-tutor/discussions/new?category=q-a
    about: Ask questions and get help from the community