name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: [feature, enhancement]
  - title: "🐛 Fixes"
    labels: [bug, fix]
  - title: "🧪 Tests"
    labels: [test, testing]
  - title: "🧹 Chore"
    labels: [chore, maintenance]
  - title: "🔐 Security"
    labels: [security]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
exclude-labels: [skip-changelog]
template: |
  ## Changes
  $CHANGES