name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Lint code
      run: pnpm lint
      
    - name: Type check
      run: pnpm typecheck
      
    - name: Run tests
      run: pnpm test -- --coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
    - name: Health check (conditional)
      env:
        DOTENV_CI: ${{ secrets.DOTENV_CI }}
      run: |
        if [ -n "${DOTENV_CI}" ]; then
          echo "$DOTENV_CI" > .env
          pnpm health:ci
        else
          echo "Skipping health checks - no CI secrets provided"
        fi
        
    - name: Build application
      run: pnpm build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          apps/orchestrator/dist/
          coverage/
        retention-days: 7

  e2e:
    needs: build-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run E2E tests
      run: pnpm test -- --coverage=false --reporter=default --passWithNoTests -t "orchestrator e2e"
      env:
        PORT: 9787
        timeout: 60000
        
    - name: Upload E2E logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-audit
        path: |
          audit.log
          apps/orchestrator/logs/
        if-no-files-found: ignore
        retention-days: 3

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'