name: bots-slsa-generator
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  group: bots-slsa-generator-${{ github.ref }}
  cancel-in-progress: true
jobs:
  slsa-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
        with:
          base64-subjects: ${{ hashFiles('**') }}
          upload-assets: true
          dry-run: false