name: bots-lint
on:
  pull_request:
  push: { branches: ["main"] }
concurrency:
  group: bots-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Super Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          FILTER_REGEX_EXCLUDE: "node_modules/|dist/|build/"