name: bots-vitest-coverage
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: bots-vitest-coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  vitest-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Vitest with coverage
        run: pnpm test --coverage
      - name: Comment coverage report
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          working-directory: .