name: bots-semgrep
on:
  pull_request:
permissions:
  contents: read
  security-events: write
concurrency:
  group: bots-semgrep-${{ github.ref }}
  cancel-in-progress: true
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/tssec
            p/react
            p/javascript
            p/typescript
            p/security-audit
          generateSarif: "1"
          generateGitHubSummary: "1"
          generateGitHubAnnotations: "1"