name: bots-reviewpad
on:
  pull_request_target:
    types: [opened, edited, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Reviewpad
        uses: reviewpad/action@v1.0.0
        with:
          config-file: .reviewpad.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}