name: bots-label-sync
on: [workflow_dispatch]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/label-sync.yml
          token: ${{ secrets.GITHUB_TOKEN }}