name: bots-auto-assign
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: bots-auto-assign-${{ github.ref }}
  cancel-in-progress: true
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.2
        with:
          configuration-path: '.github/auto-assign.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}