name: bots-dependency-review
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: bots-dependency-review-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, GPL-2.0, GPL-3.0, LGPL-2.1, LGPL-3.0
          deny-licenses: GPL-1.0, AGPL-1.0, AGPL-3.0
          comment-summary-in-pr: always