name: bots-commitlint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: bots-commitlint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}