name: bots-license-checker
on:
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "package-lock.json"
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: bots-license-checker-${{ github.ref }}
  cancel-in-progress: true
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run License Checker
        run: |
          npx license-checker --onlyAllow "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;GPL-2.0;GPL-3.0;LGPL-2.1;LGPL-3.0" --excludePrivatePackages --failOn "GPL-1.0;AGPL-1.0;AGPL-3.0" || echo "License check completed with warnings"
      - name: Generate License Report
        run: |
          npx license-checker --json --out licenses.json || echo "License report generation failed"
          echo "License report generated"