name: Gitleaks

on:
  pull_request: {}
  push: { branches: [ main, develop ] }
  schedule:
    - cron: "0 3 * * *" # optional nightly scan

permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan full history when needed

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .gitleaks.toml
          redact: true
          sarif-file-output: gitleaks.sarif
          verbose: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif