name: Gitleaks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: "0 3 * * *" # optional nightly scan

permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan full history when needed

      - name: Run Gitleaks
        id: gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Fail workflow if leaks detected
        if: steps.gitleaks.outcome == 'failure'
        run: exit 1