name: MCP Sanity (No-Key)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate .cursor/mcp.json
        run: jq empty .cursor/mcp.json
      - name: Confirm write scope is limited
        run: |
          ALLOWED=$(jq -r '.mcpServers["fs-local"].permissions.write[]' .cursor/mcp.json | tr '\n' ' ')
          echo "Write-scope: $ALLOWED"
          case "$ALLOWED" in
            *"tests"* ) : ;; * ) echo "Missing tests/ in write scope" && exit 1 ;; esac