name: Quality Gate

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: |
          if grep -q '"typecheck":' package.json; then pnpm run typecheck; else echo "No typecheck script"; fi

      - name: Lint
        run: |
          if grep -q '"lint":' package.json; then pnpm run lint; else echo "No lint script"; fi

      - name: Test
        env:
          CI: "true"
        run: |
          if grep -q '"test":' package.json; then pnpm run test -- --reporter=verbose || pnpm run test; else echo "No test script"; fi
