name: Security & QA
on: [pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: pnpm i --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm audit --audit-level=moderate || true
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci p/javascript p/typescript p/react
          generateSarif: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif