name: Semgrep

on:
  pull_request: {}
  push: { branches: [ main, develop ] }

permissions:
  contents: read
  security-events: write

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml       # uses your repo’s config
          generateSarif: true
          sarifFile: semgrep.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif