name: SuperClaude Quality

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write  # needed for SARIF upload

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install (fast)
        run: pnpm install --frozen-lockfile

      - name: Semgrep (generate SARIF)
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >
            p/ci p/javascript p/typescript p/react
          generateSarif: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ steps.semgrep.outputs.sarif != '' }}
        with:
          sarif_file: ${{ steps.semgrep.outputs.sarif }}